apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-glibb-api
spec:
  selector:
    matchLabels:
      app: create-glibb-api
  template:
    metadata:
      labels:
        app: create-glibb-api
    spec:
      containers:
      - name: create-glibb-api
        image: create-glibb-api:0.2
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
