name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      - name: Build and push create-glibb-api
        uses: docker/build-push-action@v3
        with:
          context: src/backend/services/create-glibb/
          file: src/backend/services/create-glibb/CreateGlibb.Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/create-glibb-api:latest
      - name: Build and push create-glibb-messageservice
        uses: docker/build-push-action@v3
        with:
          context: src/backend/services/create-glibb/
          file: src/backend/services/create-glibb/CreateGlibb.MessageService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/create-glibb-messageservice:latest